/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Admin
 */
public class TrangChuGUI extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuGUI
     */
    public TrangChuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_SideBar = new javax.swing.JPanel();
        jPanel_Admin = new javax.swing.JPanel();
        jLabel_Admin = new javax.swing.JLabel();
        jPanel_ChucNang = new javax.swing.JPanel();
        jLabel_TrangChu = new javax.swing.JLabel();
        jLabel_QLloaisach = new javax.swing.JLabel();
        jLabel_QLNXB = new javax.swing.JLabel();
        jLabel_QLTacGia = new javax.swing.JLabel();
        jLabel_QLsach = new javax.swing.JLabel();
        jLabel_QLthemuon = new javax.swing.JLabel();
        jLabel_QLmuon = new javax.swing.JLabel();
        jLabel_QLtra = new javax.swing.JLabel();
        jLabel_TKvaBC = new javax.swing.JLabel();
        jLabel_Dangxuat = new javax.swing.JLabel();
        jPanel_Main = new javax.swing.JPanel();
        jPanel_TrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel_QLloaisach = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_TheLoai = new javax.swing.JTable();
        SLSach_TheLoai = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_IDLoaiSach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_TenLoaiSach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SLCL_TheLoai = new javax.swing.JTextField();
        jButton_CapNhatTL = new javax.swing.JButton();
        jButton_XoaTL = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TimKiem_TheLoai = new javax.swing.JTextField();
        jButton_TimKiem_TheLoai = new javax.swing.JButton();
        jButton_ThemTheLoai = new javax.swing.JButton();
        ViewAll_TheLoai = new javax.swing.JButton();
        jPanel_QLsach = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel_QLNXB = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField_TimKiem_NXB = new javax.swing.JTextField();
        jButton_TimKiem_NXB = new javax.swing.JButton();
        jButton_ThemNXB = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_NXB = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_IDNXB = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_TenNXB = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SLCL_NXB = new javax.swing.JTextField();
        jButton_CapNhatNXB = new javax.swing.JButton();
        jButton_XoaNXB = new javax.swing.JButton();
        SLSach_NXB = new javax.swing.JSpinner();
        ViewAll_NXB = new javax.swing.JButton();
        jPanel_QLTacGia = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_TimKiem_TacGia = new javax.swing.JTextField();
        jButton_TimKiem_TacGia = new javax.swing.JButton();
        jButton_ThemTacGia = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_TacGia = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_IDTacGia = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_TenTacGia = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        SLCL_TacGia = new javax.swing.JTextField();
        jButton_CapNhatTacGia = new javax.swing.JButton();
        jButton_XoaTacGia = new javax.swing.JButton();
        SLSach_TacGia = new javax.swing.JSpinner();
        ViewAll_TacGia = new javax.swing.JButton();
        jPanel_QLThe = new javax.swing.JPanel();
        jPanel_QLMuon = new javax.swing.JPanel();
        jPanel_QLTra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setPreferredSize(new java.awt.Dimension(1930, 1010));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 0));

        jPanel_SideBar.setPreferredSize(new java.awt.Dimension(250, 1010));
        jPanel_SideBar.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel_Admin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Admin.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel_Admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lib.png"))); // NOI18N
        jLabel_Admin.setText(" ADMIN");
        jLabel_Admin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel_Admin.setIconTextGap(10);

        javax.swing.GroupLayout jPanel_AdminLayout = new javax.swing.GroupLayout(jPanel_Admin);
        jPanel_Admin.setLayout(jPanel_AdminLayout);
        jPanel_AdminLayout.setHorizontalGroup(
            jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel_AdminLayout.setVerticalGroup(
            jPanel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jPanel_SideBar.add(jPanel_Admin, java.awt.BorderLayout.PAGE_START);

        jPanel_ChucNang.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ChucNang.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        jLabel_TrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trangchu.png"))); // NOI18N
        jLabel_TrangChu.setText("Trang chủ");
        jLabel_TrangChu.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_TrangChu);

        jLabel_QLloaisach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLloaisach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLloaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loaisach.png"))); // NOI18N
        jLabel_QLloaisach.setText("Quản lí loại sách");
        jLabel_QLloaisach.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_QLloaisach);

        jLabel_QLNXB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLNXB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/publisher.png"))); // NOI18N
        jLabel_QLNXB.setText("Quản lí NXB");
        jPanel_ChucNang.add(jLabel_QLNXB);

        jLabel_QLTacGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLTacGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editor.png"))); // NOI18N
        jLabel_QLTacGia.setText("Quản lí Tác giả");
        jPanel_ChucNang.add(jLabel_QLTacGia);

        jLabel_QLsach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLsach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_mana.png"))); // NOI18N
        jLabel_QLsach.setText("Quản lí sách");
        jLabel_QLsach.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_QLsach);

        jLabel_QLthemuon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLthemuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLthemuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/the.png"))); // NOI18N
        jLabel_QLthemuon.setText("Quản lí thẻ mượn");
        jLabel_QLthemuon.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_QLthemuon);

        jLabel_QLmuon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLmuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLmuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/muon.png"))); // NOI18N
        jLabel_QLmuon.setText("Quản lí mượn");
        jLabel_QLmuon.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_QLmuon);

        jLabel_QLtra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_QLtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QLtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tra.png"))); // NOI18N
        jLabel_QLtra.setText("Quản lí trả");
        jLabel_QLtra.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_QLtra);

        jLabel_TKvaBC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TKvaBC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TKvaBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thongke.png"))); // NOI18N
        jLabel_TKvaBC.setText("Thống kê và báo cáo");
        jLabel_TKvaBC.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_TKvaBC);

        jLabel_Dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dxuat.png"))); // NOI18N
        jLabel_Dangxuat.setText("Đăng xuất");
        jLabel_Dangxuat.setIconTextGap(10);
        jPanel_ChucNang.add(jLabel_Dangxuat);

        jPanel_SideBar.add(jPanel_ChucNang, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_SideBar, java.awt.BorderLayout.LINE_START);

        jPanel_Main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Main.setLayout(new java.awt.CardLayout());

        jPanel_TrangChu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.jpg"))); // NOI18N

        jLabel3.setText("Quy định ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("dfghjkzxcvbnmzertyuicvbnjjj");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Chính sách mượn trả sách");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("yẻth5ntynruymynybvcxdsza\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel_TrangChuLayout = new javax.swing.GroupLayout(jPanel_TrangChu);
        jPanel_TrangChu.setLayout(jPanel_TrangChuLayout);
        jPanel_TrangChuLayout.setHorizontalGroup(
            jPanel_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TrangChuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
        );
        jPanel_TrangChuLayout.setVerticalGroup(
            jPanel_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TrangChuLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Main.add(jPanel_TrangChu, "card2");

        jPanel_QLloaisach.setBackground(new java.awt.Color(255, 255, 255));

        jTable_TheLoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_TheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thể loại", "Tên thể loại", "Số lượng sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_TheLoai);

        SLSach_TheLoai.setBackground(new java.awt.Color(255, 255, 255));
        SLSach_TheLoai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin loại sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        SLSach_TheLoai.setPreferredSize(new java.awt.Dimension(300, 732));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Mã loại sách");

        jTextField_IDLoaiSach.setEditable(false);
        jTextField_IDLoaiSach.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_IDLoaiSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tên loại sách");

        jTextField_TenLoaiSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Số lượng sách");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Số lượng còn lại");

        SLCL_TheLoai.setEditable(false);
        SLCL_TheLoai.setBackground(new java.awt.Color(255, 255, 255));
        SLCL_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_CapNhatTL.setBackground(new java.awt.Color(255, 255, 51));
        jButton_CapNhatTL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CapNhatTL.setText("Cập nhật");

        jButton_XoaTL.setBackground(new java.awt.Color(255, 51, 51));
        jButton_XoaTL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_XoaTL.setText("Xóa loại sách");

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout SLSach_TheLoaiLayout = new javax.swing.GroupLayout(SLSach_TheLoai);
        SLSach_TheLoai.setLayout(SLSach_TheLoaiLayout);
        SLSach_TheLoaiLayout.setHorizontalGroup(
            SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SLSach_TheLoaiLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SLCL_TheLoai, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_IDLoaiSach, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_TenLoaiSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addGroup(SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_CapNhatTL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_XoaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        SLSach_TheLoaiLayout.setVerticalGroup(
            SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SLSach_TheLoaiLayout.createSequentialGroup()
                .addGroup(SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SLSach_TheLoaiLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton_CapNhatTL))
                    .addGroup(SLSach_TheLoaiLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_IDLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SLSach_TheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TenLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_XoaTL))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SLCL_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tìm kiếm:");

        jTextField_TimKiem_TheLoai.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField_TimKiem_TheLoai.setText("Nhập thông tin tìm kiếm......");

        jButton_TimKiem_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_TimKiem_TheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton_TimKiem_TheLoai.setText("Tìm kiếm");

        jButton_ThemTheLoai.setBackground(new java.awt.Color(204, 255, 255));
        jButton_ThemTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ThemTheLoai.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ThemTheLoai.setText("Thêm thể loại");

        ViewAll_TheLoai.setBackground(new java.awt.Color(242, 242, 242));
        ViewAll_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ViewAll_TheLoai.setText("Xem tất cả");

        javax.swing.GroupLayout jPanel_QLloaisachLayout = new javax.swing.GroupLayout(jPanel_QLloaisach);
        jPanel_QLloaisach.setLayout(jPanel_QLloaisachLayout);
        jPanel_QLloaisachLayout.setHorizontalGroup(
            jPanel_QLloaisachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLloaisachLayout.createSequentialGroup()
                .addGroup(jPanel_QLloaisachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_QLloaisachLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addGroup(jPanel_QLloaisachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(SLSach_TheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)))
                    .addGroup(jPanel_QLloaisachLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jTextField_TimKiem_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_TimKiem_TheLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewAll_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ThemTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(973, Short.MAX_VALUE))
        );
        jPanel_QLloaisachLayout.setVerticalGroup(
            jPanel_QLloaisachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLloaisachLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel_QLloaisachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TimKiem_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiem_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ThemTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAll_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(SLSach_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jPanel_Main.add(jPanel_QLloaisach, "card3");

        jPanel_QLsach.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Tìm kiếm theo:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField1.setText("Nhập thông tin muốn tìm kiếm...");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "<html><center style='font-size: 16px'>Mã sách</html>", "<html><center style='font-size: 18px'>Tên sách</html>", "<html><center style='font-size: 18px; '>Thể loại</html>", "<html><center style='font-size: 18px; '>Tác giả</html>", "<html><center style='font-size: 18px; '>Nhà xuất bản</html>", "<html><center style='font-size: 18px; '>Năm xuất bản</html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Nhà xuất bản" }));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Thêm sách mới");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mã sách");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tên sách");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Năm xuất bản");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Thể loại");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tác giả");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Nhà xuất bản");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Cập nhật");

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Xóa sách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel19)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 316, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel12.setText("Thể loại");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Tác giả");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Nhà xuất bản");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel_QLsachLayout = new javax.swing.GroupLayout(jPanel_QLsach);
        jPanel_QLsach.setLayout(jPanel_QLsachLayout);
        jPanel_QLsachLayout.setHorizontalGroup(
            jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                .addGroup(jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(810, Short.MAX_VALUE))
        );
        jPanel_QLsachLayout.setVerticalGroup(
            jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                .addGroup(jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_QLsachLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QLsachLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_QLsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jPanel_Main.add(jPanel_QLsach, "card4");

        jPanel_QLNXB.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Tìm kiếm:");

        jTextField_TimKiem_NXB.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField_TimKiem_NXB.setText("Nhập thông tin tìm kiếm......");

        jButton_TimKiem_NXB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_TimKiem_NXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton_TimKiem_NXB.setText("Tìm kiếm");

        jButton_ThemNXB.setBackground(new java.awt.Color(204, 255, 255));
        jButton_ThemNXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ThemNXB.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ThemNXB.setText("Thêm NXB");

        jTable_NXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_NXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NXB", "Tên nhà xuất bản", "Số lượng sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable_NXB);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin NXB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 732));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Mã NXB");

        jTextField_IDNXB.setEditable(false);
        jTextField_IDNXB.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_IDNXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Tên NXB");

        jTextField_TenNXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Số lượng sách");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Số lượng còn lại");

        SLCL_NXB.setEditable(false);
        SLCL_NXB.setBackground(new java.awt.Color(255, 255, 255));
        SLCL_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_CapNhatNXB.setBackground(new java.awt.Color(255, 255, 51));
        jButton_CapNhatNXB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CapNhatNXB.setText("Cập nhật");

        jButton_XoaNXB.setBackground(new java.awt.Color(255, 51, 51));
        jButton_XoaNXB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_XoaNXB.setText("Xóa NXB");

        SLSach_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SLSach_NXB.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SLSach_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SLCL_NXB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(jTextField_TenNXB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_IDNXB, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel22))
                        .addGap(159, 159, 159)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_CapNhatNXB, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jButton_XoaNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IDNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CapNhatNXB))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton_XoaNXB)))
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SLSach_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SLCL_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        ViewAll_NXB.setBackground(new java.awt.Color(242, 242, 242));
        ViewAll_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewAll_NXB.setText("Xem tất cả");

        javax.swing.GroupLayout jPanel_QLNXBLayout = new javax.swing.GroupLayout(jPanel_QLNXB);
        jPanel_QLNXB.setLayout(jPanel_QLNXBLayout);
        jPanel_QLNXBLayout.setHorizontalGroup(
            jPanel_QLNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLNXBLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addGroup(jPanel_QLNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(jPanel_QLNXBLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TimKiem_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_TimKiem_NXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewAll_NXB)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ThemNXB))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                .addContainerGap(975, Short.MAX_VALUE))
        );
        jPanel_QLNXBLayout.setVerticalGroup(
            jPanel_QLNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLNXBLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel_QLNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ThemNXB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_QLNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_TimKiem_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_TimKiem_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewAll_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jPanel_Main.add(jPanel_QLNXB, "card5");

        jPanel_QLTacGia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Tìm kiếm:");

        jTextField_TimKiem_TacGia.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField_TimKiem_TacGia.setText("Nhập thông tin tìm kiếm......");

        jButton_TimKiem_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_TimKiem_TacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton_TimKiem_TacGia.setText("Tìm kiếm");

        jButton_ThemTacGia.setBackground(new java.awt.Color(204, 255, 255));
        jButton_ThemTacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ThemTacGia.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ThemTacGia.setText("Thêm tác giả");

        jTable_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_TacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tác giả", "Tên tác giả", "Số lượng sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable_TacGia);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tác giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 732));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Mã tác giả");

        jTextField_IDTacGia.setEditable(false);
        jTextField_IDTacGia.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_IDTacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Tên tác giả");

        jTextField_TenTacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Số lượng sách");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Số lượng còn lại");

        SLCL_TacGia.setEditable(false);
        SLCL_TacGia.setBackground(new java.awt.Color(255, 255, 255));
        SLCL_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_CapNhatTacGia.setBackground(new java.awt.Color(255, 255, 51));
        jButton_CapNhatTacGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CapNhatTacGia.setText("Cập nhật");

        jButton_XoaTacGia.setBackground(new java.awt.Color(255, 51, 51));
        jButton_XoaTacGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_XoaTacGia.setText("Xóa tác giả");

        SLSach_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SLSach_TacGia.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SLSach_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SLCL_TacGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(jTextField_TenTacGia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_IDTacGia, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel27))
                        .addGap(159, 159, 159)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_CapNhatTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_XoaTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IDTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CapNhatTacGia))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton_XoaTacGia)))
                .addGap(27, 27, 27)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SLSach_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SLCL_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        ViewAll_TacGia.setBackground(new java.awt.Color(242, 242, 242));
        ViewAll_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ViewAll_TacGia.setText("Xem tất cả");

        javax.swing.GroupLayout jPanel_QLTacGiaLayout = new javax.swing.GroupLayout(jPanel_QLTacGia);
        jPanel_QLTacGia.setLayout(jPanel_QLTacGiaLayout);
        jPanel_QLTacGiaLayout.setHorizontalGroup(
            jPanel_QLTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLTacGiaLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addGroup(jPanel_QLTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(jPanel_QLTacGiaLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TimKiem_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_TimKiem_TacGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewAll_TacGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ThemTacGia))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                .addContainerGap(975, Short.MAX_VALUE))
        );
        jPanel_QLTacGiaLayout.setVerticalGroup(
            jPanel_QLTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QLTacGiaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel_QLTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ThemTacGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_QLTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_TimKiem_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_TimKiem_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewAll_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Main.add(jPanel_QLTacGia, "card6");

        javax.swing.GroupLayout jPanel_QLTheLayout = new javax.swing.GroupLayout(jPanel_QLThe);
        jPanel_QLThe.setLayout(jPanel_QLTheLayout);
        jPanel_QLTheLayout.setHorizontalGroup(
            jPanel_QLTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2257, Short.MAX_VALUE)
        );
        jPanel_QLTheLayout.setVerticalGroup(
            jPanel_QLTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1266, Short.MAX_VALUE)
        );

        jPanel_Main.add(jPanel_QLThe, "card7");

        javax.swing.GroupLayout jPanel_QLMuonLayout = new javax.swing.GroupLayout(jPanel_QLMuon);
        jPanel_QLMuon.setLayout(jPanel_QLMuonLayout);
        jPanel_QLMuonLayout.setHorizontalGroup(
            jPanel_QLMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel_QLMuonLayout.setVerticalGroup(
            jPanel_QLMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel_Main.add(jPanel_QLMuon, "card8");

        javax.swing.GroupLayout jPanel_QLTraLayout = new javax.swing.GroupLayout(jPanel_QLTra);
        jPanel_QLTra.setLayout(jPanel_QLTraLayout);
        jPanel_QLTraLayout.setHorizontalGroup(
            jPanel_QLTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel_QLTraLayout.setVerticalGroup(
            jPanel_QLTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel_Main.add(jPanel_QLTra, "card9");

        getContentPane().add(jPanel_Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SLCL_NXB;
    private javax.swing.JTextField SLCL_TacGia;
    private javax.swing.JTextField SLCL_TheLoai;
    private javax.swing.JSpinner SLSach_NXB;
    private javax.swing.JSpinner SLSach_TacGia;
    private javax.swing.JPanel SLSach_TheLoai;
    private javax.swing.JButton ViewAll_NXB;
    private javax.swing.JButton ViewAll_TacGia;
    private javax.swing.JButton ViewAll_TheLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_CapNhatNXB;
    private javax.swing.JButton jButton_CapNhatTL;
    private javax.swing.JButton jButton_CapNhatTacGia;
    private javax.swing.JButton jButton_ThemNXB;
    private javax.swing.JButton jButton_ThemTacGia;
    private javax.swing.JButton jButton_ThemTheLoai;
    private javax.swing.JButton jButton_TimKiem_NXB;
    private javax.swing.JButton jButton_TimKiem_TacGia;
    private javax.swing.JButton jButton_TimKiem_TheLoai;
    private javax.swing.JButton jButton_XoaNXB;
    private javax.swing.JButton jButton_XoaTL;
    private javax.swing.JButton jButton_XoaTacGia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Admin;
    private javax.swing.JLabel jLabel_Dangxuat;
    private javax.swing.JLabel jLabel_QLNXB;
    private javax.swing.JLabel jLabel_QLTacGia;
    private javax.swing.JLabel jLabel_QLloaisach;
    private javax.swing.JLabel jLabel_QLmuon;
    private javax.swing.JLabel jLabel_QLsach;
    private javax.swing.JLabel jLabel_QLthemuon;
    private javax.swing.JLabel jLabel_QLtra;
    private javax.swing.JLabel jLabel_TKvaBC;
    private javax.swing.JLabel jLabel_TrangChu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Admin;
    private javax.swing.JPanel jPanel_ChucNang;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_QLMuon;
    private javax.swing.JPanel jPanel_QLNXB;
    private javax.swing.JPanel jPanel_QLTacGia;
    private javax.swing.JPanel jPanel_QLThe;
    private javax.swing.JPanel jPanel_QLTra;
    private javax.swing.JPanel jPanel_QLloaisach;
    private javax.swing.JPanel jPanel_QLsach;
    private javax.swing.JPanel jPanel_SideBar;
    private javax.swing.JPanel jPanel_TrangChu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_NXB;
    private javax.swing.JTable jTable_TacGia;
    private javax.swing.JTable jTable_TheLoai;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField_IDLoaiSach;
    private javax.swing.JTextField jTextField_IDNXB;
    private javax.swing.JTextField jTextField_IDTacGia;
    private javax.swing.JTextField jTextField_TenLoaiSach;
    private javax.swing.JTextField jTextField_TenNXB;
    private javax.swing.JTextField jTextField_TenTacGia;
    private javax.swing.JTextField jTextField_TimKiem_NXB;
    private javax.swing.JTextField jTextField_TimKiem_TacGia;
    private javax.swing.JTextField jTextField_TimKiem_TheLoai;
    // End of variables declaration//GEN-END:variables
}
