/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author ADMIN
 */
public class MainBookMana extends javax.swing.JPanel {

    /**
     * Creates new form Title_TrangChu
     */
    public MainBookMana() {
        initComponents();
        setSize(new Dimension(this.getMaximumSize().width, this.getMaximumSize().height));
        jButtonbS.setBackground(Color.white);
        revalidate();
        repaint();
        jPanel_msin.add(new InfoUpdateBook());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbS = new javax.swing.JButton();
        jPanel_ttl = new javax.swing.JPanel();
        jButton_ttcN = new javax.swing.JButton();
        jPanel_msin = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jButtonbS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonbS.setText("Thêm các bản sách");
        jButtonbS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbSActionPerformed(evt);
            }
        });
        add(jButtonbS);
        jButtonbS.setBounds(280, 0, 220, 35);

        jPanel_ttl.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ttl.setLayout(null);

        jButton_ttcN.setBackground(new java.awt.Color(153, 204, 255));
        jButton_ttcN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ttcN.setText("Thông tin và cập nhật sách");
        jButton_ttcN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ttcNActionPerformed(evt);
            }
        });
        jPanel_ttl.add(jButton_ttcN);
        jButton_ttcN.setBounds(0, 0, 280, 35);

        add(jPanel_ttl);
        jPanel_ttl.setBounds(0, 0, 1670, 35);

        jPanel_msin.setLayout(null);
        add(jPanel_msin);
        jPanel_msin.setBounds(0, 40, 1670, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ttcNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ttcNActionPerformed
        jButton_ttcN.setBackground(new java.awt.Color(153, 204, 255));
        jButtonbS.setBackground(Color.white);
        jPanel_msin.removeAll();
        // Cập nhật lại giao diện
        revalidate();
        repaint();
        jPanel_msin.add(new InfoUpdateBook());
    }//GEN-LAST:event_jButton_ttcNActionPerformed

    private void jButtonbSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbSActionPerformed
        jButtonbS.setBackground(new java.awt.Color(153, 204, 255));
        jButton_ttcN.setBackground(Color.white);
        jPanel_msin.removeAll();
        // Cập nhật lại giao diện
        revalidate();
        repaint();
        jPanel_msin.add(new AddBookCopy());
    }//GEN-LAST:event_jButtonbSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ttcN;
    private javax.swing.JButton jButtonbS;
    private javax.swing.JPanel jPanel_msin;
    private javax.swing.JPanel jPanel_ttl;
    // End of variables declaration//GEN-END:variables
}
