/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author ADMIN
 */
public class MainCardMana extends javax.swing.JPanel {

    /**
     * Creates new form Title_TrangChu
     */
    public MainCardMana() {
        initComponents();
        jButton_seachCard.setBackground(Color.white);
        setSize(new Dimension(this.getMaximumSize().width, this.getMaximumSize().height));
        jPanel_main.add(new ActivateTheCardGUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_seachCard = new javax.swing.JButton();
        jButton_listCard = new javax.swing.JButton();
        jPanel_title = new javax.swing.JPanel();
        jPanel_main = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jButton_seachCard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_seachCard.setText("Tìm kiếm thẻ");
        jButton_seachCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_seachCardActionPerformed(evt);
            }
        });
        add(jButton_seachCard);
        jButton_seachCard.setBounds(280, 0, 180, 35);

        jButton_listCard.setBackground(new java.awt.Color(153, 204, 255));
        jButton_listCard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_listCard.setText("Quản lý danh sách thẻ");
        jButton_listCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listCardActionPerformed(evt);
            }
        });
        add(jButton_listCard);
        jButton_listCard.setBounds(0, 0, 280, 35);

        jPanel_title.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_title.setLayout(null);
        add(jPanel_title);
        jPanel_title.setBounds(0, 0, 1670, 35);

        jPanel_main.setLayout(null);
        add(jPanel_main);
        jPanel_main.setBounds(0, 40, 1670, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_listCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listCardActionPerformed
        jButton_listCard.setBackground(new java.awt.Color(153, 204, 255));
        jButton_seachCard.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new ActivateTheCardGUI());
    }//GEN-LAST:event_jButton_listCardActionPerformed

    private void jButton_seachCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_seachCardActionPerformed
         jButton_seachCard.setBackground(new java.awt.Color(153, 204, 255));
        jButton_listCard.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new SearchForCardGUI());
    }//GEN-LAST:event_jButton_seachCardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_listCard;
    private javax.swing.JButton jButton_seachCard;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_title;
    // End of variables declaration//GEN-END:variables
}
