/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author ADMIN
 */
public class MainReaderMana extends javax.swing.JPanel {

    /**
     * Creates new form Title_TrangChu
     */
    public MainReaderMana() {
        initComponents();
        jButton_infoReader.setBackground(new java.awt.Color(153, 204, 255));
        jButton_searchReader.setBackground(Color.white);
        setSize(new Dimension(this.getMaximumSize().width, this.getMaximumSize().height));
        jPanel_main.add(new ReaderGUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_searchReader = new javax.swing.JButton();
        jButton_infoReader = new javax.swing.JButton();
        jPanel_ttl = new javax.swing.JPanel();
        jPanel_main = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jButton_searchReader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_searchReader.setText("Tìm kiếm độc giả");
        jButton_searchReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchReaderActionPerformed(evt);
            }
        });
        add(jButton_searchReader);
        jButton_searchReader.setBounds(280, 0, 180, 35);

        jButton_infoReader.setBackground(new java.awt.Color(153, 204, 255));
        jButton_infoReader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_infoReader.setText("Quản lý thông tin độc giả");
        jButton_infoReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_infoReaderActionPerformed(evt);
            }
        });
        add(jButton_infoReader);
        jButton_infoReader.setBounds(0, 0, 280, 35);

        jPanel_ttl.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ttl.setLayout(null);
        add(jPanel_ttl);
        jPanel_ttl.setBounds(0, 0, 1670, 35);

        jPanel_main.setLayout(null);
        add(jPanel_main);
        jPanel_main.setBounds(0, 40, 1670, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_infoReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_infoReaderActionPerformed
        jButton_infoReader.setBackground(new java.awt.Color(153, 204, 255));
        jButton_searchReader.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new ReaderGUI());
    }//GEN-LAST:event_jButton_infoReaderActionPerformed

    private void jButton_searchReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchReaderActionPerformed
         jButton_searchReader.setBackground(new java.awt.Color(153, 204, 255));
        jButton_infoReader.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new ReaderSearchGUI());
    }//GEN-LAST:event_jButton_searchReaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_infoReader;
    private javax.swing.JButton jButton_searchReader;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_ttl;
    // End of variables declaration//GEN-END:variables
}
