/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author ADMIN
 */
public class MainLoanMana extends javax.swing.JPanel {

    /**
     * Creates new form Title_TrangChu
     */
    public MainLoanMana() {
        initComponents();
        jButtonchDK.setBackground(Color.white);
        jButton_daDK.setBackground(Color.white);
        setSize(new Dimension(this.getMaximumSize().width, this.getMaximumSize().height));
        jPanel_main.add(new DanhSachPMGUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ttl = new javax.swing.JPanel();
        jButtonchDK = new javax.swing.JButton();
        jButton_daDK = new javax.swing.JButton();
        jButton_listPhieu = new javax.swing.JButton();
        jPanel_main = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel_ttl.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ttl.setLayout(null);

        jButtonchDK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonchDK.setText("Phiếu mượn chưa đăng ký");
        jButtonchDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonchDKActionPerformed(evt);
            }
        });
        jPanel_ttl.add(jButtonchDK);
        jButtonchDK.setBounds(480, 0, 260, 35);

        jButton_daDK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_daDK.setText("Phiếu mượn đã đăng ký");
        jButton_daDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_daDKActionPerformed(evt);
            }
        });
        jPanel_ttl.add(jButton_daDK);
        jButton_daDK.setBounds(200, 0, 280, 35);

        jButton_listPhieu.setBackground(new java.awt.Color(153, 204, 255));
        jButton_listPhieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_listPhieu.setText("Danh sách phiếu");
        jButton_listPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listPhieuActionPerformed(evt);
            }
        });
        jPanel_ttl.add(jButton_listPhieu);
        jButton_listPhieu.setBounds(0, 0, 200, 40);

        add(jPanel_ttl);
        jPanel_ttl.setBounds(0, 0, 1670, 35);

        jPanel_main.setLayout(null);
        add(jPanel_main);
        jPanel_main.setBounds(0, 40, 1670, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_daDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_daDKActionPerformed
        jButton_daDK.setBackground(new java.awt.Color(153, 204, 255));
        jButtonchDK.setBackground(Color.white);
        jButton_listPhieu.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new PhieuDKMuonGUI());
    }//GEN-LAST:event_jButton_daDKActionPerformed

    private void jButtonchDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonchDKActionPerformed
        jButtonchDK.setBackground(new java.awt.Color(153, 204, 255));
        jButton_daDK.setBackground(Color.white);
        jButton_listPhieu.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new PhieuMuonGUI());
    }//GEN-LAST:event_jButtonchDKActionPerformed

    private void jButton_listPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listPhieuActionPerformed
        jButton_listPhieu.setBackground(new java.awt.Color(153, 204, 255));
        jButton_daDK.setBackground(Color.white);
        jButtonchDK.setBackground(Color.white);
        jPanel_main.removeAll();
            // Cập nhật lại giao diện
            revalidate();
            repaint();
            jPanel_main.add(new DanhSachPMGUI());
    }//GEN-LAST:event_jButton_listPhieuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_daDK;
    private javax.swing.JButton jButton_listPhieu;
    private javax.swing.JButton jButtonchDK;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_ttl;
    // End of variables declaration//GEN-END:variables
}
