package GUI;

import BUS.CT_PhieuMuonBUS;
import BUS.CT_PhieuTraBUS;
import BUS.PhieuTraBUS;
import BUS.SachBUS;
import DTO.CT_PhieuMuonDTO;
import DTO.CT_PhieuTraDTO;
import DTO.PhieuTraDTO;
import BUS.PhieuMuonBUS;
import DTO.PhieuMuonDTO;
import DTO.SachDTO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class TraSachGUI extends javax.swing.JFrame {

    /**
     * Creates new form TraSachGUI
     *
     */
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    private final String maPM;
    PhieuTraBUS ptBUS;
    SachBUS sachBUS;
    PhieuMuonBUS pmBUS;
    CT_PhieuTraBUS ctptBUS;
    CT_PhieuMuonBUS ctpmBUS;
    ArrayList<String> tinhTrangSach = new ArrayList<>(List.of("Nguyên vẹn", "Hư hỏng nhẹ", "Hư hỏng nặng", "Mất"));
    private TrangChuGUI tc;
    
    public TraSachGUI(String maPM) throws SQLException {
        initComponents();
        this.setTitle("Giao diện trả sách");
        pmBUS = new PhieuMuonBUS();
        ptBUS = new PhieuTraBUS();
        ctptBUS = new CT_PhieuTraBUS();
        ctpmBUS = new CT_PhieuMuonBUS();
        sachBUS = new SachBUS();
        this.maPM = maPM;
        Calendar calendar = Calendar.getInstance();
        String ngaytra = formatter.format(calendar.getTime());
        txt_NgayTra.setText(ngaytra);
        display(maPM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_TinhTrangSach = new javax.swing.JTable();
        btn_TraSach = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_PhiTreHan = new javax.swing.JTextField();
        txt_NgayMuon = new javax.swing.JTextField();
        txt_NgayTra = new javax.swing.JTextField();
        btn_TinhPhiTreHan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_HanTra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_PhiDenBu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_MaPM = new javax.swing.JTextField();
        txt_TienCoc = new javax.swing.JTextField();
        txt_MaThe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_TinhPhiDenBu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_SoLanGiaHan = new javax.swing.JTextField();
        btn_TinhTongTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 1010));
        setPreferredSize(new java.awt.Dimension(1130, 1010));

        jPanel1.setPreferredSize(new java.awt.Dimension(1241, 64));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN TRẢ SÁCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2), "Tình trạng sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(51, 153, 255))); // NOI18N

        tbl_TinhTrangSach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_TinhTrangSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><center style='font-size:16px'>Mã sách</html>", "<html><center style='font-size:16px'>Tên sách</html>", "<html><center style='font-size:16px'>Số lượng</html>", "<html><center style='font-size:16px'>Tình trạng mượn</html>", "<html><center style='font-size:16px'>Tình trạng trả</html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TinhTrangSach.setRowHeight(25);
        jScrollPane1.setViewportView(tbl_TinhTrangSach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_TraSach.setBackground(new java.awt.Color(204, 255, 255));
        btn_TraSach.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TraSach.setForeground(new java.awt.Color(255, 51, 51));
        btn_TraSach.setText("XÁC NHẬN TRẢ SÁCH");
        btn_TraSach.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true));
        btn_TraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraSachActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Tổng tiền phải trả:");

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("VND");

        txt_PhiTreHan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_NgayMuon.setEditable(false);
        txt_NgayMuon.setBackground(new java.awt.Color(255, 255, 255));
        txt_NgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_NgayTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_TinhPhiTreHan.setBackground(new java.awt.Color(204, 255, 255));
        btn_TinhPhiTreHan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_TinhPhiTreHan.setText("Tính phí trễ hạn");
        btn_TinhPhiTreHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhPhiTreHanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Ngày mượn");

        txt_HanTra.setEditable(false);
        txt_HanTra.setBackground(new java.awt.Color(255, 255, 255));
        txt_HanTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Hạn trả");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Phí trễ hạn");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Ngày trả");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Mã thẻ");

        txt_PhiDenBu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tiền cọc");

        txt_MaPM.setEditable(false);
        txt_MaPM.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaPM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TienCoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_MaThe.setEditable(false);
        txt_MaThe.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaThe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Phí đền bù");

        btn_TinhPhiDenBu.setBackground(new java.awt.Color(204, 255, 255));
        btn_TinhPhiDenBu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_TinhPhiDenBu.setText("Tính phí đền bù");
        btn_TinhPhiDenBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhPhiDenBuActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Mã phiếu mượn");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Số lần gia hạn");

        txt_SoLanGiaHan.setEditable(false);
        txt_SoLanGiaHan.setBackground(new java.awt.Color(255, 255, 255));
        txt_SoLanGiaHan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_TinhTongTien.setBackground(new java.awt.Color(204, 255, 255));
        btn_TinhTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_TinhTongTien.setText("Tính tổng tiền");
        btn_TinhTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MaPM, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txt_TienCoc, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txt_MaThe, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_NgayTra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txt_HanTra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_NgayMuon, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_SoLanGiaHan))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel12))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_PhiTreHan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_PhiDenBu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_TraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(btn_TinhPhiTreHan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_TinhPhiDenBu)
                                .addGap(123, 123, 123)
                                .addComponent(btn_TinhTongTien)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_MaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(txt_NgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txt_PhiDenBu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_MaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_HanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(txt_PhiTreHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txt_TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(txt_SoLanGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TinhPhiTreHan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TinhPhiDenBu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TinhTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btn_TraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraSachActionPerformed
        String id = maPM.replace("PM", "PT");
        String maThe = txt_MaThe.getText();
        String ngayMuon = txt_NgayMuon.getText();
        String ngayTra = txt_NgayTra.getText();
        double phiDenBu = Double.parseDouble(txt_PhiDenBu.getText());
        double phiTreHan = Double.parseDouble(txt_PhiTreHan.getText());
        String trangThai = "";
        if (phiTreHan > 0) {
            trangThai = "Trễ hạn";
        } else {
            trangThai = "Đúng hạn";
        }
        Date nt = null, nm = null;
        try {
            nm = formatter.parse(ngayMuon);
            nt = formatter.parse(ngayTra);
        } catch (ParseException ex) {
            Logger.getLogger(TraSachGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date ngaymuon = new java.sql.Date(nm.getTime());
        java.sql.Date ngaytra = new java.sql.Date(nt.getTime());
        PhieuTraDTO ptDTO = new PhieuTraDTO(id, maPM, maThe, ngaymuon, ngaytra, phiDenBu, phiTreHan, trangThai);
        if (ptBUS.addPhieuTra(ptDTO)) {
            ArrayList<CT_PhieuTraDTO> dsCTPT = new ArrayList<>();
            for (int row = 0; row < tbl_TinhTrangSach.getRowCount(); row++) {
                String idSach = tbl_TinhTrangSach.getValueAt(row, 0).toString();
                String tenSach = tbl_TinhTrangSach.getValueAt(row, 1).toString();
                int soLuong = Integer.parseInt(tbl_TinhTrangSach.getValueAt(row, 2).toString());
                String tinhTrang = tbl_TinhTrangSach.getValueAt(row, 4).toString();
                dsCTPT.add(new CT_PhieuTraDTO(id, idSach, tenSach, soLuong, tinhTrang));
            }
            if (ctptBUS.addCT_PhieuTra(dsCTPT)) {
                PhieuMuonDTO pm = pmBUS.searchPhieuMuonByMaPhieuMuon(maPM);
                pm.setTrangThai("Đã trả");
                pmBUS.updateTrangThaiPhieuMuon(pm);
                try {
                    tc = new TrangChuGUI();
                    tc.AddRowToDSPhieuTra(ptDTO);
                    tc.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(TraSachGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                JOptionPane.showMessageDialog(rootPane,
                "Tạo phiếu trả " + maPM + " cho người dùng có mã thẻ là " + maThe + " thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tạo phiếu trả thất bại!", id, HEIGHT);
        }

    }//GEN-LAST:event_btn_TraSachActionPerformed

    private void btn_TinhPhiDenBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhPhiDenBuActionPerformed
        double tongPhi = 0;
        int quantityRow = tbl_TinhTrangSach.getRowCount();
        for (int i = 0; i < quantityRow; i++) {
            String idSach = tbl_TinhTrangSach.getValueAt(i, 0).toString();
            String TTtruoc = tbl_TinhTrangSach.getValueAt(i, 3).toString();
            String TTsau = tbl_TinhTrangSach.getValueAt(i, 4).toString();
            double gia = sachBUS.getSachById(tbl_TinhTrangSach.getValueAt(i, 0).toString()).getGiaSach();
            int indexTTtruoc = tinhTrangSach.indexOf(TTtruoc);
            int indexTTsau = tinhTrangSach.indexOf(TTsau);            
            double tong = 0;
            int ct = indexTTsau - indexTTtruoc;
            if(indexTTsau == 3){
                tong = gia * 1.1;
                SachDTO sach = sachBUS.getSachById(idSach);
                sach.setSoLuong(sach.getSoLuong()-1);
                sachBUS.updateSach(sach);
            }
            if(indexTTtruoc == 0){
                if(ct == 1){
                    tong =  gia * 0.2;
                }
                if(ct == 2){
                    tong = gia * 0.8;
                }
            } else{
                if(ct == 1){
                    tong =  gia * 0.5;
                }
            }
            tongPhi += tong;
                                   
        }
        txt_PhiDenBu.setText(String.format("%.2f", tongPhi));
    }//GEN-LAST:event_btn_TinhPhiDenBuActionPerformed

    private void btn_TinhPhiTreHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhPhiTreHanActionPerformed
        String hanTra = txt_HanTra.getText();
        String ngayTRA = txt_NgayTra.getText();
        
        Date ht = null, nt = null;
        try {
            nt = formatter.parse(ngayTRA);
            ht = formatter.parse(hanTra);
        } catch (ParseException ex) {
            Logger.getLogger(TraSachGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date hantra = new java.sql.Date(ht.getTime());
        java.sql.Date ngaytra = new java.sql.Date(nt.getTime());
        int songay = ptBUS.TinhSoNgay(ngaytra, hantra);
        int slSach = tbl_TinhTrangSach.getRowCount();
        double phitrehan = songay * slSach * 1000.0;
        txt_PhiTreHan.setText(String.format("%.2f", phitrehan));
    }//GEN-LAST:event_btn_TinhPhiTreHanActionPerformed

    private void btn_TinhTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTongTienActionPerformed
        double tongTien = 0.0;
        double phiTreHan = Double.parseDouble(txt_PhiTreHan.getText());
        double phiDenBu = Double.parseDouble(txt_PhiDenBu.getText());
        double tienCoc = Double.parseDouble(txt_TienCoc.getText());
        int solan = Integer.parseInt(txt_SoLanGiaHan.getText());
        tongTien = phiTreHan + phiDenBu + 10000.0 * solan - tienCoc;
        txt_TongTien.setText(String.format("%.2f", tongTien));
    }//GEN-LAST:event_btn_TinhTongTienActionPerformed

    private void display(String maPM) {
        PhieuMuonDTO pmDTO = pmBUS.searchPhieuMuonByMaPhieuMuon(maPM);
        txt_MaPM.setText(maPM);
        txt_MaThe.setText(pmDTO.getMaThe());
        txt_TienCoc.setText(pmDTO.getTienCoc() + "");
        txt_NgayMuon.setText(pmDTO.getNgayMuon() + "");
        txt_HanTra.setText(pmDTO.getHanTra() + "");
        txt_SoLanGiaHan.setText(pmDTO.getSoLanGiaHan() + "");
        DefaultTableModel tinhtrangNhanSach = (DefaultTableModel) tbl_TinhTrangSach.getModel();
        tinhtrangNhanSach.setRowCount(0);
        CT_PhieuMuonDTO ctpm;
        ArrayList<CT_PhieuMuonDTO> ds = ctpmBUS.getCT_PhieuMuonByPhieuMuonId(maPM);
        for (int i = 0; i < ds.size(); i++) {
            ctpm = ds.get(i);
            Object[] row = {ctpm.getMaSach(), ctpm.getTenSach(), ctpm.getSoLuong(), ctpm.getTrangThai()};
            tinhtrangNhanSach.addRow(row);
        }
        String[] options = {"Nguyên vẹn", "Hư hỏng nhẹ", "Hư hỏng nặng", "Mất"};
        JComboBox<String> cbb = new JComboBox<>(options);
        cbb.setFont(new java.awt.Font("Segoe", java.awt.Font.PLAIN, 16));
        TableColumn column = tbl_TinhTrangSach.getColumnModel().getColumn(4);
        column.setCellEditor(new javax.swing.DefaultCellEditor(cbb));
    }

//    public void updateButtonStatus(boolean trasach, boolean capnhat) {
//        btn_TraSach.setEnabled(trasach);
//        btn_CapNhatPhieuTra.setEnabled(capnhat);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TinhPhiDenBu;
    private javax.swing.JButton btn_TinhPhiTreHan;
    private javax.swing.JButton btn_TinhTongTien;
    private javax.swing.JButton btn_TraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_TinhTrangSach;
    private javax.swing.JTextField txt_HanTra;
    private javax.swing.JTextField txt_MaPM;
    private javax.swing.JTextField txt_MaThe;
    private javax.swing.JTextField txt_NgayMuon;
    private javax.swing.JTextField txt_NgayTra;
    private javax.swing.JTextField txt_PhiDenBu;
    private javax.swing.JTextField txt_PhiTreHan;
    private javax.swing.JTextField txt_SoLanGiaHan;
    private javax.swing.JTextField txt_TienCoc;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
